### ISSUE TITLE
Can't Make on Mac

### ISSUE THREAD

**Issue by rtconner** [mfaerevaag/wd-c#2]
When I run `make` on my Mac, I get an error ..

```
~/wd-c (master) $ make
rm -rf bin/*
cd src && /Library/Developer/CommandLineTools/usr/bin/make -f Makefile.src
cc -W -pedantic -Werror -Wall -std=gnu99 -fno-strict-aliasing -fno-common -Wno-unused-parameter -fstrict-aliasing -fstrict-overflow -Wno-return-local-addr -O3 -c config.c -o ../bin/config.o
error: unknown warning option '-Wno-return-local-addr'; did you mean
      '-Wno-return-stack-address'? [-Werror,-Wunknown-warning-option]
make[1]: *** [../bin/config.o] Error 1
make: *** [build] Error 2
```

**Comment by mfaerevaag** [comment]
Thanks for reporting!

All the warning flags might be a bit overkill so I removed all, but the `-Wall` one (and `-std=gnu99`). Could you pull and try again?

**Comment by rtconner** [comment]
Make works. Now I get an error on `make install`
```
~/install/wd-c (master) $ make install
install -Dm755 bin/wd /usr/bin/_wd
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

**Comment by mfaerevaag** [comment]
Seems like Mac OS X's `install(1)` has different arguments than Linux's. I therefore removed the `-D` option which is named `-d` on OS X. The `-m` argument should be the same for both.

Please pull and try again. 

Haven't tried to install on Mac OS X, so it's nice to get these things fixed for the next guy 👍

**Comment by rtconner** [comment]
Not sure what is up with this.

```
~/install/wd-c (master) $ make install
install -m755 bin/wd /usr/bin/_wd
install: /usr/bin/_wd: Operation not permitted
make: *** [install] Error 71
~/install/wd-c (master) $ sudo make install
Password:
install -m755 bin/wd /usr/bin/_wd
install: /usr/bin/_wd: Operation not permitted
make: *** [install] Error 71
```

**Comment by rtconner** [comment]
I tried manually copying the file, but had issues on that too.

**Comment by mfaerevaag** [comment]
Apparently OS X El Captian doesn't let you install to `/usr/bin` anymore, it should be `/usr/local`. If you would yet again pull and make.

Thanks for your patience.. If it for some reason doesn't work again I'll get a friend with a Mac to do it, so you don't have to be the crash test dummy.

**Comment by rtconner** [comment]
Nothing new pulled down. Did you push?

**Comment by mfaerevaag** [comment]
Sorry, must have forgot. Just pushed.

**Comment by mfaerevaag** [comment]
Should I close?
